### ISSUE TITLE
when use `duration`, the video doesn't show anything.

### ISSUE THREAD

**Issue by kingsimba** [samirkumardas/jmuxer#105]
I use jMuxer with Angular.

When I use `fps`, it works as expected:

```
<video #rgbCameraPlayer autoplay playsinline *ngIf="supportsRgbCamera" class="camera-video"></video>
```

```
this.jmuxer = new JMuxer({
            node: this.rgbCameraPlayer.nativeElement,
            mode: 'video',
            fps: 10,
        });
```

But when I remove `fps`, and use `duration` instead. The video is totally blank.

Input data contains the timestamp of each frame: https://gist.github.com/kingsimba/71798025f97b196c3ee80f23f81a7584

The input data is 10 fps and contains one iframe for each 20 frames.

Code snippet:

```ts
class MyComponent implements AfterViewInit{
    private jmuxer: JMuxer = null;
    private lastFrame : RgbCameraData = null;

    ngAfterViewInit(): void {
        this.jmuxer = new JMuxer({
            node: this.rgbCameraPlayer.nativeElement,
            mode: 'video',
            debug: false
        });
    }

    private onCameraData(frame: RgbCameraData) {
        if (this.jmuxer != null) {
            if (this.lastFrame != null)
            {
                const duration = Math.floor((frame.stamp - this.lastFrame.stamp) * 1000); // to milliseconds
                this.jmuxer.feed({
                    video: this.lastFrame.data,
                    duration: duration
                });
            }
        }

        this.lastFrame = frame;
    }
}
```

The logs show that the frames are parsed correctly.
`jmuxer.min.js:1 jmuxer: No. of frames of the last chunk: 1`

But there is no `jmuxer.min.js:1 put segment (video): dts: 1000 frames: 1 second: 00:01`, which would have shown up if I use `fps` instead of `duration`

**Comment by samirkumardas** [comment]
The code looks good.  Did you get duration correctly?

**Comment by kingsimba** [comment]
Duration is calculated from `stamp` in https://gist.github.com/kingsimba/71798025f97b196c3ee80f23f81a7584

I added some log, the duration seems correct.

```
duration =  200
duration =  203
duration =  200
duration =  207
duration =  0
duration =  199
duration =  201
duration =  207
duration =  195
duration =  202
duration =  197
duration =  206
duration =  203
duration =  199
duration =  204
duration =  0
duration =  200
duration =  208
duration =  197
duration =  203
duration =  199
duration =  208
duration =  200
duration =  203
duration =  197
duration =  201
duration =  0
duration =  205
duration =  201
duration =  203
duration =  193
duration =  207
duration =  217
duration =  191
```

But there is a 0 duration for each iframe. Is it correct? I used [open.264](https://github.com/cisco/openh264) for encoding.

**Comment by kingsimba** [comment]
It doesn't bug me now. Remove both `fps` and `duration`, use `flush_time` instead. The video plays fine.

```ts
this.jmuxer = new JMuxer({
    node: this.rgbCameraPlayer.nativeElement,
    mode: 'video',
    flushingTime: 0,
});
```
