### ISSUE TITLE
Laggy video in chrome and edge

### ISSUE THREAD

**Issue by leo0104** [samirkumardas/jmuxer#116]
I've created a simple example to display a raw H.264 live stream in the browser. I receive raw H.264 packets from my backend.
The video shows up nicely in Firefox but very laggy on chrome or edge. I receive the `delay` console log very often in chrome and edge.

HTML:
`<video autoplay id="player"></video>`

Create JMuxer:
`jmuxer = new JMuxer({
    node: 'player',
    mode: 'video',
    debug: true,
    flushingTime: 0,
    clearBuffer: true
  })`

Feed data:
`jmuxer.feed({
      video: new Uint8Array(data)
    })`

Any ideas what I'm doing wrong?

### Update:
The delay disappears as soon as i click on the video element in the browser. Is there a way to directly display the video without lags?

**Comment by samirkumardas** [comment]
it depends on the browser media policy. Check this post https://developer.chrome.com/blog/autoplay/

**Comment by leo0104** [comment]
@samirkumardas  Thank you for your advice!

In the [blog post](https://developer.chrome.com/blog/autoplay/) you linked it says: **Muted autoplay is always allowed**

If i replace `<video autoplay id="player"></video>` with `<video autoplay muted id="player"></video>` it works!
