### ISSUE TITLE
Live stream with variable framerate

### ISSUE THREAD

**Issue by leo0104** [samirkumardas/jmuxer#118]
I receive raw H.264 frames from a live stream together with timestamps of every frame but the framerate changes during the stream. 

Is it possible to display a live stream with a variable framerate? Which configuration of JMuxer do I have to use for that scenario?

**Comment by samirkumardas** [comment]
Have you checked the option `readFpsFromTrack` ?

**Comment by leo0104** [comment]
Thank you for the hint @samirkumardas 

For the moment the solution with `readFpsFromTrack` works well :)
Unfortunately I sometimes have some lags on my video but I'm not sure if my backend is causing the problem.

I have to test a little bit more display my live stream smoothly.
