### ISSUE TITLE
<video> stops painting in Android WebView after a few frames

### ISSUE THREAD

**Issue by bmharper** [samirkumardas/jmuxer#131]
This peculiar behaviour occurs only in a WebView on Android:

When playing a video, the first few frames a drawn (for about 1 second). Then, the WebView stops painting itself. The video frames are clearly being decoded though, because if I scroll the view up and down, then I can see the video playing. So it looks like the video frames are getting decoded, but the renderer doesn't know that it needs to repaint the screen.

To be clear, this doesn't look like a bug in JMuxer. I'm going to try some workarounds, and post back here with my findings.

This ticket is for posterity, and for the chance that other people are seeing the same thing.

**Comment by bmharper** [comment]
I'm using this as a workaround:

```js
muxer.feed(data);
let cx = canvas.getContext('2d')!;
cx.fillStyle = "rgba(0,0,0,0.01)";
cx.fillRect(0, 0, 1, 1);
```

and it fixes the problem.

If I don't discover anything more about this issue, I'll come back and close it in January 2023.

**Comment by EhsanVahab** [comment]
Hi @bmharper 
I get stuck in the same problem too and unfortunately newbe in Javascript
Could you share your full example or give me more detail?

**Comment by bmharper** [comment]
Hi @EhsanVahab,
You can see the full source code of my workaround here: https://github.com/bmharper/cyclops/blob/master/www/src/components/camera/Player.vue#L208

I'm working around two issues there:
1. The original issue described in this post. If you search for `invalidateCanvas` then you'll find it in the above source file.
2. Another thing that I've discovered, which is that Android WebView fails to play video if it's a fresh page load. This is why I restart jmuxer if I notice that `webkitDecodedFrameCount` remains zero. And note that this only needs to be done once per page load.

**Comment by EhsanVahab** [comment]
> Hi @EhsanVahab, You can see the full source code of my workaround here: https://github.com/bmharper/cyclops/blob/master/www/src/components/camera/Player.vue#L208
> 
> I'm working around two issues there:
> 
>     1. The original issue described in this post. If you search for `invalidateCanvas` then you'll find it in the above source file.
> 
>     2. Another thing that I've discovered, which is that Android WebView fails to play video if it's a fresh page load. This is why I restart jmuxer if I notice that `webkitDecodedFrameCount` remains zero. And note that this only needs to be done once per page load.

Thanks for your quick response
