### ISSUE TITLE
play only audio aac will auto pause

### ISSUE THREAD

**Issue by waiter89** [samirkumardas/jmuxer#14]
play only audio aac will auto pause,when controller/buffer.js:41  doCleanup() ,it will pause,and remove doCleanup,it's ok ;
the aac format is channel = 1  freq=8000

I think is  not necessary to call doCleanup

**Comment by samirkumardas** [comment]
You can turn off buffer clearing by setting the property `clearBuffer` false.
Also you can try increasing `cleaningOffset` a larger value like 30 seconds. 

By the way,  I have set  cleaningOffset 30s  by default in today build.
