### ISSUE TITLE
x265 support 

### ISSUE THREAD

**Issue by adminy** [samirkumardas/jmuxer#18]
I was wondering if it’s possible to add x265 support, since the file format is very similar.
Also can this project have multiple audio tracks?

**Comment by samirkumardas** [comment]
Nope, Even most browsers does not support h265 https://caniuse.com/#feat=hevc

**Comment by adminy** [comment]
Safari and edge do, everybody has edge or safari by default, I have both! But that’s not really related to converting hvec or h265 and aac files into an mp4, That is my goal, not what happens next to the mp4

**Comment by samirkumardas** [comment]
My comment was in regard to browser compatibility mostly.

Basically JMuxer don't have problem with multiple tracks. Even it does not care which track's buffer you are feeding right now. All you need a resetting the audio track whenever you switch  to different track. Honestly I have never tried with multiple tracks, but it should work. It might need little tuning though.

Also You can try with x265.  I don't have any idea about difference with h264. So it's worth a try.

**Comment by dima9911** [comment]
h265 not work

**Comment by greendrake** [comment]
Bump. Browser support is now reasonable.
