### ISSUE TITLE
without audio,it can't play 

### ISSUE THREAD

**Issue by waiter89** [samirkumardas/jmuxer#2]
In docs/index.html

function parse(data) {
      var input = new Uint8Array(data),
          dv = new DataView(input.buffer),
          duration,
          audioLength,
          audio,
          video;

      duration = dv.getUint16(0, true);
      audioLength = dv.getUint16(2, true);
      audio = input.subarray(4, (audioLength + 4));
      video = input.subarray(audioLength + 4); 
      return {
        audio: audio,
        video: video,
        duration: duration
      };
 

when it return {video:video,duration:duration},it can't play the video

**Comment by samirkumardas** [comment]
If you don't need audio, then you must instantiate jmuxer with video mode. For example:

`var jmuxer = new JMuxer({
        node: 'player',
        mode: 'video'
     });`

If you still get the issue, let me know your browser name

**Comment by huangqichao** [comment]
create jmuxer like this:
var jmuxer = new JMuxer({ node: 'player', mode: 'video' });
but still get error : Input object must have video and/or audio property. Make sure it is not empty and valid typed array
my browser is : Google Chrome 80.0.3987.122（windows）
