### ISSUE TITLE
How to convert RTSP streams using ffmpeg?

### ISSUE THREAD

**Issue by kekeqy** [samirkumardas/jmuxer#22]
I want to convert the RTSP stream with ffmpeg, then transfer it through WebScoket, and finally play it through jmuxer.

**Comment by samirkumardas** [comment]
Sorry I don't know how to convert RTSP stream  to other format using ffmpeg.
If you already have RTSP stream, you can play it using rtsp player that is available on github. Not sure why do you need to convert it.

By the way, JMuxer expects raw h264 as an input data. So you must provide raw h264 with timing information (e.g either chunk duration or fps )
