### ISSUE TITLE
How to enable debug ? documentation/sample missing.

### ISSUE THREAD

**Issue by Serveurperso** [samirkumardas/jmuxer#24]
Hello,

On the sample page I always get :
TypeError: 'log' called on an object that does not implement interface Console.

Also on my code when I enable debug.

Any help ?
Pascal

**Comment by DogFive** [comment]
@Serveurperso  It's apart of options:


``` javascript
var jmuxer = new JMuxer({
        node: 'player',
        mode: 'video',
        flushingTime: 1,
        fps: 20,
        debug: true
     });
```

**Comment by Serveurperso** [comment]
This is what I used but no log showed inside console.log...
