### ISSUE TITLE
Video is really choppy once fed to jmuxer

### ISSUE THREAD

**Issue by taylorjdawson** [samirkumardas/jmuxer#29]
I created 1 second segments of an mp4 file. Concatenating them using ffmpeg works fine, however, feeding them into `jmuxer` results in really choppy playback. Although, 2 second segments work fine, but I really really want 1 second segments. 
My guess is that the segments are over lapping so it goes 
```
[ 0=1=2=3=4=5 ] [=3=4=5=6=7=8=]
     seg 1           seg 2
```
If that makes sense at all?
Thanks!

**Comment by samirkumardas** [comment]
Look like you are providing incorrect segment duration.
Do you provide segment duration while feeding i.e  jmuxer.feed?

**Comment by taylorjdawson** [comment]
Thanks for the response!

I do provide segment data while feeding jmuxer. Below you'll see how I calculate the segment duration using `ffprobe`:

```
const ffmpeg = require("fluent-ffmpeg");

const fs = require('fs');
const { promisify } = require('util');

const readFileAsync = promisify(fs.readFile);
const writeFileAsync = promisify(fs.writeFile);
const ffprobeAsync = promisify(ffmpeg.ffprobe);

const dir = 'video/'

const getAudio = (id) => readFileAsync(dir+`${id}.aac`.padStart(7,'0'));
const getVideo = (id) => readFileAsync(dir+`${id}.h264`.padStart(8,'0'));
const getVidDur = (id) => ffprobeAsync(dir+`${id}.mp4`.padStart(7,'0')).then( metadata => metadata.format.duration * 1000)

const createChunk = (videoDuration, audioDataLength, audio, video, chunk_id) => {

    const videoDurationBytes = toBytes(videoDuration);
    const audioDataLengthBytes = toBytes(audioDataLength);
    console.log({videoDuration, audioDataLength, chunk_id})
    const totalLength = videoDurationBytes.length + audioDataLengthBytes.length + audio.length + video.length;

    const chunk = Buffer.concat([videoDurationBytes, audioDataLengthBytes, audio, video], totalLength)

    return chunk
};

const toBytes = ( number ) => {
    const buf = Buffer.alloc(2); // <- 2 bytes
    buf.writeUInt16LE(number, 0);
    return buf
};

(async () => {
    for (let i = 1; i < 24 /* number of segments */; i++) {
        const audio = await getAudio(i);
        const video = await getVideo(i);
        const vidDur = await getVidDur(i);
        const chunk = createChunk(vidDur, audio.length, audio, video, i);
        writeFileAsync(`video_raw/${i}.txt`, chunk);
    }
})();
```

On the client side I use your parse function like so:
```
jmuxer.feed(parse(data));
```

**Comment by samirkumardas** [comment]
>jmuxer.feed(parse(data));

what does this data contain?  Does it include duration property?

Choppy playback could be caused by wrong duration value.

**Comment by taylorjdawson** [comment]
The data is the .txt file and I used this function that you provide:

```
  function parse(data) {
      
      let input = new Uint8Array(data),
          dv = new DataView(input.buffer),
          duration,
          audioLength,
          audio,
          video;

      duration = dv.getUint16(0, true);
      audioLength = dv.getUint16(2, true);
      audio = input.subarray(4, (audioLength + 4));
      video = input.subarray(audioLength + 4);
      return {
        audio: audio,
        video: video,
        duration: duration
      };
 }
```
to turn that raw binary data into the format required by the `jmuxer.feed()` method.

**Comment by taylorjdawson** [comment]
Okay I did some inspecting. So the audio duration somehow is different from video duration. Although that wouldn't affect the video stuttering would it?

**Comment by samirkumardas** [comment]
Audio does not affect video playing. It just can make audio and video out of sync. Little time difference is acceptable.

So you are providing 1000 to the duration field, am I right? Could you please confirm it?

**Comment by taylorjdawson** [comment]
Yes I can confirm it. I put a console.log on the data before it get's fed
```
let parsedData = parse(data);
console.log(parsedData);
jmuxer.feed(parsedData);
```


![image](https://user-images.githubusercontent.com/29665732/59885977-0e7ae280-9372-11e9-9af2-52a1996a4b0b.png)

**Comment by samirkumardas** [comment]
hmm, times look correct. If it worked for 2 seconds, it should work fine for 1 second as well.
Could you please try adjusting `flushingTime` like less than 1000?
You can adjust flushing time while instantiating JMuxer
