### ISSUE TITLE
support h264 different profile ??

### ISSUE THREAD

**Issue by flyme2012** [samirkumardas/jmuxer#3]
Can  support H264 different profiles (baseline  main  high) ?

**Comment by samirkumardas** [comment]
Only base profile :(
Basically, I was needed only base profile so I haven't considered other h264 profile though it can be achieved by doing some modifications.
By the way, MR would be much appreciated :)

**Comment by flyme2012** [comment]
yeah,my project need other h264 profile .

**Comment by flyme2012** [comment]
Can you tell where can i do some modifications to be achieved ??

**Comment by samirkumardas** [comment]
Mostly in remuxer/h264.js

**Comment by flyme2012** [comment]
no , can't use change any profile, your library is support all profile.
