### ISSUE TITLE
h264 modify 800x448 to 448x800

### ISSUE THREAD

**Issue by yinjun622** [samirkumardas/jmuxer#34]
When playing h264 video, 
modify 800x448 to 448x800, 
it can't display normally.

ffplay plays normally.
[d.h264.zip](https://github.com/samirkumardas/jmuxer/files/3530322/d.h264.zip)

**Comment by samirkumardas** [comment]
I just tested. It played fine. What issue you have having?

I just saw some distortion frames in between

**Comment by yinjun622** [comment]
> I just tested. It played fine. What issue you have having?
> 
> I just saw some distortion frames in between

some distortion frames, because of changed the screen 800x448 to 448x800.


used the jmuxer:
<img width="572" alt="屏幕快照 2019-08-26 上午10 13 54" src="https://user-images.githubusercontent.com/988571/63660793-aec60b00-c7ea-11e9-80bf-f56f46f990f9.png">
(00:00:14)

used the ffplay:
<img width="598" alt="屏幕快照 2019-08-26 上午10 14 55" src="https://user-images.githubusercontent.com/988571/63660795-af5ea180-c7ea-11e9-9900-c017519123d2.png">
(00:00:14)

**Comment by samirkumardas** [comment]
Have you clicked play button? It won't start automatically.  I am getting as same as ffplay

**Comment by yinjun622** [comment]
Yes, I clicked play button.
and ffplay can be played automatically on my mac .
```
$ ffplay d.h264
ffplay version 4.1.4 Copyright (c) 2003-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1.4_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-12.0.1.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-12.0.1.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
```
but my question is that when the width and height are changed, it can't be shown like ffplay.
<img width="1499" alt="屏幕快照 2019-08-26 下午1 35 54" src="https://user-images.githubusercontent.com/988571/63667532-beebe380-c806-11e9-9fac-70eaf6896b19.png">

**Comment by jithingangadharan** [comment]
> Sorry I was extremely busy for the last few weeks. I got your point. Basically I do not re-fetch PPS and SPS once it I got it unless you reset it manually. Please check [this](https://github.com/samirkumardas/jmuxer/blob/ea877d6ada2106432f835fd3a0ac558df95458f4/src/parsers/h264.js#L249) to get an idea. Basically you can adjust code there if you want to fetch PPS and SPS every time and of-course it is performance issue

==> How to make re-fecth PPS and SPS based on the size size change dynamically ?

**Comment by jithingangadharan** [comment]
> Yes, I clicked play button.
> and ffplay can be played automatically on my mac .
> 
> ```
> $ ffplay d.h264
> ffplay version 4.1.4 Copyright (c) 2003-2019 the FFmpeg developers
>   built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
>   configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1.4_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-12.0.1.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-12.0.1.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
> ```
> 
> but my question is that when the width and height are changed, it can't be shown like ffplay.
> <img alt="屏幕快照 2019-08-26 下午1 35 54" width="1499" src="https://user-images.githubusercontent.com/988571/63667532-beebe380-c806-11e9-9fac-70eaf6896b19.png">

Did you find the solution?

**Comment by darak1** [comment]
> Sorry I was extremely busy for the last few weeks. I got your point. Basically I do not re-fetch PPS and SPS once it I got it unless you reset it manually. Please check [this](https://github.com/samirkumardas/jmuxer/blob/ea877d6ada2106432f835fd3a0ac558df95458f4/src/parsers/h264.js#L249) to get an idea. Basically you can adjust code there if you want to fetch PPS and SPS every time and of-course it is performance issue

can you please tell me how to fetch PPS and SPS everytime.actually i removed both  if  if (!this.track.pps) { } and for sps also still getting the same error

**Comment by SANSA27** [comment]
was this issue fixed.
