### ISSUE TITLE
1920x1080 stream with choppy video

### ISSUE THREAD

**Issue by jozefchutka** [samirkumardas/jmuxer#35]
Hi Samir, thanks for the great lib!

I have recenlty played with jmuxer, but experienced very choppy video when used with ffmpeg desktop streaming and fullhd video. I put together a small demo to showcase:

demo.js (`node demo.js`)
```
const WebSocket = require('ws');
const spawn = require('child_process').spawn;
const shell = "ffmpeg -f gdigrab -framerate 30 -video_size 1920x1080 -i desktop "
	+ "-an -c:v h264 -preset ultrafast "
	+ "-f rawvideo -";

new WebSocket.Server({port:8080}).on('connection', function(ws) {
	spawn(shell, [], {shell:true}).stdout.on('data', data => {
		ws.send(data);
	});
});
```

demo.html
```
<!DOCTYPE html>
<html>
<head><script type="text/javascript" src="jmuxer.js"></script></head>
<body><video id="player" width="640" height="480" controls="false" autoplay muted></video></body>
<script>
window.onload = function startup() {
	const jmuxer = new JMuxer({node:'player', mode:'video', flushingTime:1});
	const ws = new WebSocket("ws://localhost:8080/");
	ws.binaryType = "arraybuffer";
	ws.addEventListener('message', event => {
		jmuxer.feed({video:new Uint8Array(event.data)});
	});
}
</script>
</html>
```

the rendered video looks as following:
![Clipboard01](https://user-images.githubusercontent.com/750041/71253156-554c9380-2327-11ea-86f2-ce48c4bc8a83.jpg)

When feeding the same stream into ffplay `ffmpeg -f gdigrab -framerate 30 -video_size 1920x1080 -i desktop -an -c:v h264 -preset ultrafast -f rawvideo - | ffplay -i -` it renders just ok.

Do you have any idea what can be done to make the redering complete?

**Comment by jozefchutka** [comment]
I managed to resolve it by restricting bitrate. It seems there is some kind of bottleneck on client side related to processing large amount of data on socket or on jmuxer side.

**Comment by samirkumardas** [comment]
Glad to hear. I will check it out when I get some time. I assume it is a WebSocket issue. I have also encountered data congestion issue with WebSocket and it is expected.

**Comment by samirkumardas** [comment]
Probable duplicate issue https://github.com/samirkumardas/jmuxer/issues/44

**Comment by jozefchutka** [comment]
Checked with the latest jmuxer.min.js it seems improved but still not perfect. Now a larger part of image is rendered ok, however artifacts appears further down when streaming 1920x1080

**Comment by samirkumardas** [comment]
I just tested with 1920x1080 and found it good.

Sample file: [sample_1920x1080.h264](https://drive.google.com/file/d/1NO-bQgugrVE0A81XmWltQKks-DJSVh9K/view?usp=sharing)
You can test yourself https://samirkumardas.github.io/jmuxer/h264_player.html

Could you please share a clip for which you are having a problem so I can test myself?

**Comment by jozefchutka** [comment]
I am not able to replicate the issue using static file. I will need to investigate further. Keep the issue closed and consider resolved. Thanks

**Comment by samirkumardas** [comment]
Ok.

FYI, jMuxer considers each chunk/packet (i.e. data that you feed each time) as a complete buffer of the frame(s). If you feed buffer with partial frames, it may cause.

In future updates, I will try to handle it. For now,  it should be handled before feeding e.g. on the Server-end
