### ISSUE TITLE
Can not play without audio

### ISSUE THREAD

**Issue by huangqichao** [samirkumardas/jmuxer#36]
create jmuxer like this:
var jmuxer = new JMuxer({ node: 'player', mode: 'video' });
but still get error : Input object must have video and/or audio property. Make sure it is not empty and valid typed array
my browser is : Google Chrome 80.0.3987.122（windows）

**Comment by samirkumardas** [comment]
Provide the full code please

**Comment by huangqichao** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description"
          content="jMuxer - a simple javascript mp4 muxer for non-standard streaming communications protocol">
    <meta name="keywords" content="h264 player, mp4 player, mse, mp4 muxing, jmuxer, aac player">
    <title>JMuxer demo</title>
</head>
<body>
<div id="container" style="width: 600px;height:900px; margin: 0 auto;">
    <video width="600px" height="900px" controls autoplay poster="images/loader-thumb.jpg" id="player"></video>
</div>
<script>

    window.onload = function () {
        var socketURL = 'ws://localhost:8000';
        var jmuxer = new JMuxer({
            node: 'player',
            mode: 'video',
            fps: 30,
            debug: true
        });

        var ws = new WebSocket(socketURL);
        ws.binaryType = 'arraybuffer';
        ws.addEventListener('message', function (event) {
            jmuxer.feed({
                video: new Uint8Array(event.data)
            });
        });

        ws.addEventListener('error', function (e) {
            console.log('Socket Error');
        });
    }

</script>
<script type="text/javascript" src="jmuxer.min.js"></script>
</body>
</html>

**Comment by samirkumardas** [comment]
hmm, code seems correct.  Looks like `event.data` is not valid.  In the example folder, there is an example that plays only video. Please check. I can just say it can play the video only.

**Comment by huangqichao** [comment]
event.data is .h264 stream data without container，from android phone。does jmuxer supports?

**Comment by samirkumardas** [comment]
Definitely it can. Actually, that's is why it is was made for. It looks like the h264 is not valid data or you are slicing incorrectly. There is a demo regarding raw h254 playing.  Please check this file https://github.com/samirkumardas/jmuxer/blob/master/example/server-h264.js

The error you are getting it simply means jMuxer fails to extract NAL units from the h264 buffers. You can debug [`extractChunks`](https://github.com/samirkumardas/jmuxer/blob/master/example/server-h264.js#L12) method to observe the data pattern.

**Comment by huangqichao** [comment]
in fact，the .h264 stream from android phone has many frames, but only one or two frames produce this error：“nput object must have video and/or audio property. Make sure it is not empty and valid typed array”，and all frames can not be played

**Comment by huangqichao** [comment]
![image](https://user-images.githubusercontent.com/20202844/76295513-b6b14c80-62ef-11ea-8d6f-279f9642b4ea.png)

the video tag looks like this

**Comment by huangqichao** [comment]
now i dont get any error. but still can not play the .h264 stream data from android phone.

**Comment by samirkumardas** [comment]
Then you can debug.  You can build the dev version, check this section https://github.com/samirkumardas/jmuxer#how-to-build

Make sure the Jmuxer fetch frames properly. In the browser log, it should print the DTS and sampling information something like `put segment video dts: 100 samples: 20 and second: 2` 
If it does not show any logs, then jmuxer is not fetching any frames at all

**Comment by huangqichao** [comment]
![image](https://user-images.githubusercontent.com/20202844/77141204-05f93900-6ab7-11ea-89d1-894eba5de962.png)
the console logs like that, and the video player still doesn't  play. So confused!

**Comment by samirkumardas** [comment]
I understand your frustration.  The number of samples seems very low. Though it depends on the video elements, however, it seems very low. 

Also, put a breakpoint at this line https://github.com/samirkumardas/jmuxer/blob/master/src/parsers/h264.js#L253 and debug what kinds of NAL unit you get on your feed. You must have SPS, PPS, and IDR.

**Comment by timofeyp** [comment]
> Definitely it can. Actually, that's is why it is was made for. It looks like the h264 is not valid data or you are slicing incorrectly. There is a demo regarding raw h254 playing. Please check this file https://github.com/samirkumardas/jmuxer/blob/master/example/server-h264.js
> 
> The error you are getting it simply means jMuxer fails to extract NAL units from the h264 buffers. You can debug [`extractChunks`](https://github.com/samirkumardas/jmuxer/blob/master/example/server-h264.js#L12) method to observe the data pattern.

Hello! Im sending correctly NAL units through WS stream to a client app with your lib, and have the same error( How to use [`extractChunks`] for debugging? The [`state`] param is always 0 and fuction return empty array on each buffer.

**Comment by samirkumardas** [comment]
Related to https://github.com/samirkumardas/jmuxer/issues/44 ?
