### ISSUE TITLE
colors are wrong, support for YUV420J?

### ISSUE THREAD

**Issue by mebenstein** [samirkumardas/jmuxer#38]
I just tried out this library and it seems to work great, except that the colors are wrong. I am not using JS or FFMPEG to encode the image, I am using Jcodec in Spring and converting my RGB source to YUV420j before encoding. Did anyone experience anything similar?

I checked if my input is not BGR, which doesn't seem to be the case. What colorspace is jmuxer expecting, do I need to convert something first?

Thanks in advance.

**Comment by samirkumardas** [comment]
jmuxer does not handle anything regarding colorspace.  Though I use a library to generate the mp4 box https://github.com/samirkumardas/jmuxer/blob/master/src/util/mp4-generator.js 
It could be related to it.
  
Can you make an mp4 file with the same color profile and play in the browser directly and check if it can play properly?

**Comment by samirkumardas** [comment]
If you get a chance, you can try the latest build if it fixes the issue
