### ISSUE TITLE
Why can't  change frame?

### ISSUE THREAD

**Issue by flyme2012** [samirkumardas/jmuxer#4]
my websocket is raw h264 frame data,only show first frame,but can't show the back of the frame?

**Comment by flyme2012** [comment]
ok. i say again.
My data is the native H264 encoding data of the frame screen. When I play it with your library, I can only display the first frame, and the rear picture can't be parsed. There are continuous data, but they do not show, freeze frames in the first frame.

Forgive me for my poor English...

**Comment by samirkumardas** [comment]
Yes I understood your case. It basically happens whenever you don't provide timing information.

Let me explain little. Assume you are making a h264 player so what would be the barefoot steps:
1.  Making a frame from h264 data (Ignoring details)
2.  Then play that frame( aka picture) for some time. But how long?  Basically it depends on timing information. You can provide timing in two ways in jMuxer. Either you can set `fps` value while instantiating Or you can provide duration when you feed media data.

Example:

**Upon instantiation** 

`var jmuxer = new JMuxer({
           node: 'player',
           fps: 24,   /* Frame per second */
           debug: false
       });`

**Upon Feed** 

`jmuxer.feed({
         audio: audio,
         video: video,
         duration: duration /* Duration of provided chunk */
 });`

Hope this helps you!

**Comment by flyme2012** [comment]
sorry,it can't work!

**Comment by flyme2012** [comment]
it's work.  because i forget to call play .
