### ISSUE TITLE
Recommended usage for minimizing memory usage

### ISSUE THREAD

**Issue by x0a** [samirkumardas/jmuxer#40]
I've got 3 instances of JMuxer running on a webpage (security system). After 1hr of usage, the page's memory usage starts to approach **1gb**.

After 2 hours of usage: ![screenshot](https://user-images.githubusercontent.com/13019784/77873795-9995dc80-7210-11ea-9282-93709652931d.png)
(The high CPU usage in the screenshot is a result of me running `video.src = ''` as a test, not part of the bug here).

The 1.6gb of memory in the screenshot is not a result of anything being stored in memory by the script (the page only consumes about 7mb of memory in heap), but I suspect it's because MSE is storing a large amount of buffered video in memory. Running `console.log(video.buffered.end(0)` results in `7500` or around 2hrs of buffered content being held in memory, per instance. And I'm able to seek using `video.currentTime = 3000`

This is my init: 
```js
        const muxer = new JMuxer({
            node: videoElement.current,
            mode: 'video',
            flushingTime: 0,
            clearBuffer: true,
            fps: 12.8,
            debug: false
        })
```
If this isn't a bug, would you happen to have any suggestions regarding how to manage memory usage?

**Comment by samirkumardas** [comment]
As you have initiated with `clearBuffer`: true, it should clear the old buffer.  So it seems that jmuxer is failing to clear the buffer.

You can put a breakpoint in this function https://github.com/samirkumardas/jmuxer/blob/master/src/controller/buffer.js#L41 to see if it really invoke.

**Comment by x0a** [comment]
Thanks, I will try that soon.

I should mention that JMuxer runs seamlessly for hours as long as the tab is in focus. If I switch tabs and leave it running for 30 mins, the tab accumulates 2mb per second. If I return to it and seek to the end, the memory is cleared. If I wait a little over an hour before returning to the tab, the video appears frozen, and occasionally I find these errors, which stop as soon as I destroy JMuxer and open a new instance. That also releases the memory:

![Untitled](https://user-images.githubusercontent.com/13019784/77950281-e4096e80-728d-11ea-9a06-2f53a3a857ce.png)

So since the videos are silent, Chrome is automatically pausing them when switching tabs (confirmed with Media dev tools), and playing once I switch back. It looks like there used to be [flags](https://superuser.com/questions/1204222/youtube-stops-playing-when-switching-chrome-tab) to disable this behavior. But they have been removed.

So the videos accumulate a large buffer while in the background. But as soon as they start playing again I seek to the end:
```ts
        const onTimeUpdate = (event: Event) => {
            const video = event.currentTarget as HTMLMediaElement;
            const curTime = video.currentTime;
            const lastBuff = video.buffered.length;
            if (lastBuff === 0) return;
            const curEnd = video.buffered.end(lastBuff - 1);

            if (curEnd - curTime > 3) {
                video.currentTime = curEnd - 1.3;
                console.log('skipped ahead')
            }
        }
        videoElement.current.addEventListener('timeupdate', onTimeUpdate);
```
Which clears the buffer and works.. unless the buffer exceeds an hour, in which case I'm unable to seek, the buffer doesn't clear, and sometimes I get those errors.

**Comment by x0a** [comment]
So a simple solution to my problem is to watch for the 'pause' event and run a interval that keeps `video.currentTime` close to `video.buffered.end(video.buffered.length - 1)`, every few seconds; clearing the interval once the 'play' event is detected.

Thanks for the prompt response and great project!

**Comment by x0a** [comment]
I am still occasionally getting the errors in https://github.com/samirkumardas/jmuxer/issues/40#issuecomment-606197309 

As a temporary fix to prevent it from killing the page, I trigger a destroy and reopen with
```js
jmuxer.mediaSource.sourceBuffers.addEventListener('removesourcebuffer', () => {
    // destroy and re-create
});
```
However I think a good long-term fix would be to JMuxer to watch for that event as well and internally create a new SourceBuffer and push any buffered muxed content to it

**Comment by samirkumardas** [comment]
Chrome browser does that trick. It stops rendering video when the tab is an inactive state as a part of the optimization. That's why jmuxer fails to clear the buffer. I will check the issue when I get a chance.

**Comment by hashqueue** [comment]
It works.
```javascript
// Vue3
const videoElements = ref([])

window.addEventListener('focus', () => {
  if (videoElements.value) {
    for (const videoElement of videoElements.value) {
      videoElement.currentTime = Math.ceil(videoElement.buffered.end(0))
      videoElement.play()
    }
  }
})
```
