### ISSUE TITLE
Invalid ADTS audio format

### ISSUE THREAD

**Issue by dmarenko** [samirkumardas/jmuxer#42]
``Input object must have video and/or audio property. Make sure it is not empty and valid typed array``

I'm getting this error when running ``server-h264.js``

The player does stream though with ``server.js``.

I'm using Windows 10 if that matters.

**Comment by samirkumardas** [comment]
You must run index-h264.html when the server is server-h264.js

**Comment by dmarenko** [comment]
Didn't notice the 2nd index. Thanks.
