### ISSUE TITLE
Chunk extraction algorithm

### ISSUE THREAD

**Issue by dmarenko** [samirkumardas/jmuxer#43]
In the ``server-h264.js`` demo, the chunks are sliced so the headers are at the end of the chunk, instead of the beginning, is this normal (they're essentially footers, instead of headers)?

This seems also to be the case for the NALs inside ``/raw/``.

In my personal project, I'm transmitting the NALs with the 0x000001 or 0x00000001 constants at the beginning of the NAL unit (as headers), but nothing is rendered (also no errors).

I'm using H264 with baseline profile, and I'm including PPS and SPS headers on every I-frame.

**Comment by samirkumardas** [comment]
It was incorrectly implemented that's why it manifested some artifacts in some cases. I have updated the script in the latest build.  thank you
