### ISSUE TITLE
Decoding artefacts

### ISSUE THREAD

**Issue by headlessme** [samirkumardas/jmuxer#44]
First of all, thanks for this great library, I've got it working for one of my projects for live streaming video data. There's a couple of instances where I'm seeing a lot of decoding artefacts like this:

<img width="148" src="https://user-images.githubusercontent.com/4320942/81168862-b4860a00-8f8f-11ea-85e4-2c2a18071e25.png">

I'm not seeing any errors on the console or in chrome://media-internals. The data that generally exhibits this issues are non-standard resolutions, e.g. the screenshot above was from video at 42x90. For video at 1680x1050 everything works great.

I've tried passing the raw h264 data (annex b, baseline) through ffmpeg to generate an mp4. This generates a video without any of the same encoding issues shown above, so I think the h264 data I have is good. I'm using this command for ffmpeg:

```
ffmpeg -framerate 10 -i /tmp/frames/all.h264 -c copy ./output.mp4
```

Any idea how I can resolve these decoding issues? Happy to provide sample data if that's helpful.

**Comment by samirkumardas** [comment]
resolution 42x90? Such too small? Franky I have never tested with this small size.

I could try but passing very busy days :(

**Comment by headlessme** [comment]
Thanks for the fast response. That example was from a very tiny resolution stream, but I've also seen it at other resolutions:

Landscape resolutions:
504x315
554x346
588x368
638x399

Portrait resolutions:
413x895
1239x2685

The artefacting look very similar in these resolutions too. Any help you can offer in resolving this would be really appreciated :)

**Comment by psande** [comment]
I'm having the same problem. Same type of green background and blocky artefacts. Did you find a solution? @headlessme

**Comment by headlessme** [comment]
Not really, we found some small issues with the way we were generating timestamps / frame ordering which fixed a few things, but frames from the iOS simulator still end up with artefacts like this.

**Comment by javascripet** [comment]
It happens to me sometime. Exactly the same "green issue"

**Comment by psande** [comment]
Thanks @headlessme and @javascripet. I will let you know if I find anything.

**Comment by darak1** [comment]
facing the same issue can anyone please tell if they found any solution

**Comment by headlessme** [comment]
My best guess at the moment is that we see this issue where frames have been sliced across multiple NALUs. @samirkumardas should this case be handled already?

**Comment by headlessme** [comment]
I've looked into this a bit more. I think what's happening is that when a frame is split into multiple slices the logic in `getVideoFrames()` is treating each NALU that's actually a slice of a frame as a complete frame:

https://github.com/samirkumardas/jmuxer/blob/dbd5a1937df71f237dd2ab71756e6bf8788f92cf/src/jmuxer.js#L124-L126

This means that frames can end up split across multiple mdat boxes in the mp4, which I think isn't allowed. Not sure what's needed to fix this, maybe looking at the frame_num in the slice headers?

**Comment by headlessme** [comment]
Happens for all profiles, slight different artefacting for each. I'm using output from the h264 encoder in the iOS simulator which seems to reliably generate sliced frames. I can provide a sample h264 file if helpful.

**Comment by samirkumardas** [comment]
If you provide a sample, that would be great. Thank you

**Comment by darak1** [comment]
> I've looked into this a bit more. I think what's happening is that when a frame is split into multiple slices the logic in `getVideoFrames()` is treating each NALU that's actually a slice of a frame as a complete frame:
> 
> https://github.com/samirkumardas/jmuxer/blob/dbd5a1937df71f237dd2ab71756e6bf8788f92cf/src/jmuxer.js#L124-L126
> 
> This means that frames can end up split across multiple mdat boxes in the mp4, which I think isn't allowed. Not sure what's needed to fix this, maybe looking at the frame_num in the slice headers?

found fix ?

**Comment by darak1** [comment]
> If you provide a sample, that would be great. Thank you

found any fix ???

**Comment by darak1** [comment]
hi you found any solution for the issue decoding artifacts#44 jmuxer?

**Comment by samirkumardas** [comment]
Fixed. https://github.com/samirkumardas/jmuxer/commit/1605823dba08fc585f8e5c35f56360e5921c7ef2
