### ISSUE TITLE
Safari Memory Usage

### ISSUE THREAD

**Issue by sanalpencere** [samirkumardas/jmuxer#46]
Hello everyone,

First of all @samirkumardas thanks for this great library. I just implemented your library to play raw H264 frames. It works perfectly. I am getting data from a web socket and feeding the video element with jmuxer. There is no problem with Firefox and Chrome. But When I try to use safari, memory usages is getting increase so much. I realized that Chrome and Firefox clear video when I checked the video element control, the duration is always between 2 and 3 seconds. But in Safari, it is increasing.

Do you have any suggestions to make? I tried to debug it but I couldn't find any clue about this issue.

**Comment by samirkumardas** [comment]
Sorry, passing very busy days. Will check when I get a chance

**Comment by samirkumardas** [comment]
I was not able to generate the issue. It cleared the buffer in Safari v13.1.2 properly.

Can you try playing the example index-h264.html and the corresponding server js file? let me know if you get the same issue

**Comment by sanalpencere** [comment]
@samirkumardas thanks for your support. I will check and inform you again.
