### ISSUE TITLE
Live streaming with jmuxer

### ISSUE THREAD

**Issue by mikezks** [samirkumardas/jmuxer#48]
You mentioned it was purpose of developing this project to make this possible:

> It was needed to play raw H264 and AAC data coming from live streaming encapsulated into a custom transport container in a project

I would like to use a live stream from an enigma2 receiver source which supports H264/AAC/ADTS.

Are there any examples publicly available on how to use a stream resource instead of a static file or static chunks?

Anyway, thank you very much for your great work!

**Comment by samirkumardas** [comment]
Thank you.
Unfortunately, no opensource code example is available for live streaming.

However, the approach is the almost same as the static version.  Also, the static version is not actually static, it loops forever to replicate the live streaming.
