### ISSUE TITLE
Improvement - allow "live" streaming by ditching data

### ISSUE THREAD

**Issue by tzah4748** [samirkumardas/jmuxer#54]
I would like to offer an improvement to support more real live streaming.

Assume the following :
1. jMuxer is getting its data from some external source via WebSocket.
2. jMuxer refreshes frequently and with constant 60 fps.
3. the <video> tag has attributes of "autoplay" and "muted" so the video is shown as live as possible.

**The problem:**
While all works fine and well, changing Tabs in chrome (for example) will cause the <video> to stop playing, but the data keeps coming from the WebSocket and is appended to the video length.
Which will cause the video to be shown in a very big delay once i go back to the "streaming" tab.

**Suggestions:** (one of the following i assume)
1. Skip to the end of the video (flag) when tab gets focus again / <video> starts playing again.
2. Ignoring any "data" (not config) NAL Units coming when tab isn't focused.
3. Not appending any data (again not config) to the MSE while the <video> isn't playing.

These are just some of the suggestions came to my mind, i would be happy with anything that solves that "problem".

Many thanks.

**Comment by samirkumardas** [comment]
Thanks but why don't you apply this logic on your application end?  You are feeding buffer yourself from your application end, so you can implement this logic on your end.
