### ISSUE TITLE
H265 not compatible

### ISSUE THREAD

**Issue by sarbajitpal8** [samirkumardas/jmuxer#58]
It's there any way to make this library work for h265, or else can you suggest h265 library for muxing like JMuxer. And JMuxer works brilliantly, thank you.

**Comment by kuzux** [comment]
Doing that would be very helpful for our use case as well. jmuxer works great with h.264, adding support for h.265/hevc doesn't look like it needs a huge change since jmuxer doesn't need to decode the whole stream but only parse the nal units.

**Comment by samirkumardas** [comment]
Let the Chrome browser support it at least. https://caniuse.com/hevc
