### ISSUE TITLE
#hacktoberfest

### ISSUE THREAD

**Issue by psande** [samirkumardas/jmuxer#59]
Hi!

I was wondering if you would be open to add the hacktoberfest hashtag to your project?

I have a few PR's I would like to send over (including a new feature) and it would be awesome it they counted towards the event.

Here are the rules: https://hacktoberfest.digitalocean.com/hacktoberfest-update

Also, amazing project. Works great and opens a lot of possibilities! Thanks for your work!

**Comment by samirkumardas** [comment]
sure thing. added. Thank you

**Comment by psande** [comment]
Thanks!
