### ISSUE TITLE
It's me again!

### ISSUE THREAD

**Issue by flyme2012** [samirkumardas/jmuxer#6]
hi. it's me again! i'm sorry .
Your project is running well, but there is a problem with delay. It is necessary to collect enough frames to display these pictures continuously, and not to display them in one frame or one frame. My project is not a continuous video stream, so sometimes there is only one frame that needs to be displayed, so your library can't be displayed.
can you help me please ?

**Comment by samirkumardas** [comment]
have tried adjusting `flushingTime` property? By default it consider 1500 ms that is bit high. You can change to 200 or 300 ms. thanks

**Comment by flyme2012** [comment]
no , it can't  work!  i change to 30 ms. i must keep show every frame in time.

**Comment by samirkumardas** [comment]
Do you have any hosted URL to check?

**Comment by samirkumardas** [comment]
Please check this issue https://github.com/samirkumardas/jmuxer/issues/7
It might be related with IDR

**Comment by flyme2012** [comment]
yeah, i see your answer.
but  i think my question can't be solve , because i need every frame and can't delay when i receiver frame data by websocket .
My project is Cloud virtual machine and the frame data's transmission isn't continuous ,so my screen maybe receiver B-frame then stop receiver frame data, so my screen is stop and can't show last frame .

i can't know do you understande me .

if you have perfer answer ,please tell me ,  thank you .

**Comment by samirkumardas** [comment]
If you have any hosted URL, let me know. thanks
