### ISSUE TITLE
How to interpret the debug output

### ISSUE THREAD

**Issue by AlexSapple** [samirkumardas/jmuxer#61]
Hi, 

just looking at the debug (whilst trying to improve video quality of a live stream) - would it be possible to clarify what the debug output means -

![image](https://user-images.githubusercontent.com/30351641/97563447-f6da5200-19da-11eb-969c-1ecfdb5148b3.png)

can you fill in the blanks for me (or explain If I have got some of this wrong)? 

* No. frames in the last chunk = The actual number of frames that Jmuxer has ingested in the chunk of data given
* put segment (video):  = ?? appears to be an increasing count during playback
* dts = ??
* gop = group of pictures (gop size? - how many individual images/frames make up this (segment?))
* second = the cumulative duration in seconds of playback

@samirkumardas you helped me out greatly with a previous question around quality (and I'm really grateful), but I'm still playing around with data at each end (both the source of the stream and the front end browser playback) - I'm looking for the "sweet spot" of how often to feed data in to Jmuxer - things like how often to push data down the socket at the server side - one thing that interests me from the debug - when I _believe that I'm packaging up 10 frames in a GOP_ Jmuxer doesn't often agree in the "no. frames in last chunk". Similarly to the question of partial frames, are there also challenges around frame delimiters (detecting where a frame ends) - I only ask that question as a complete beginner in the subject! :)

**Comment by samirkumardas** [comment]
google :)

**Comment by AlexSapple** [comment]
very well I suppose.
