### ISSUE TITLE
Exception using live streaming

### ISSUE THREAD

**Issue by yeshivsher** [samirkumardas/jmuxer#63]
Uncaught DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
    at i.value (http://localhost:3000/static/js/1.chunk.js:238752:93)
    at n.value (http://localhost:3000/static/js/1.chunk.js:238955:39)
    at http://localhost:3000/static/js/1.chunk.js:238927:56

I'm trying to use this library with socket and rabbitmq publishing h264 chunks.
it's working slow and has a delay and after a minute throw this exception.

**Comment by samirkumardas** [comment]
Make sure you are receiving data properly. 
Incorrect fps or duration causes the latency
