### ISSUE TITLE
No. of frames of the last chunk: 0

### ISSUE THREAD

**Issue by MistaHanyi** [samirkumardas/jmuxer#65]
Sorry to bother you about this. I'm totally new to this video thing. 

I got raw h.264 data from camera, and my code is like this:

```
soc.on('androidOnline', function (value) {
        console.log('androidOnline: ', value)
        if (value) {
            deviceOnline = true
    
            /**
             * start play live
             */
            soc.on('videoStream', buffer => {
                const uint8Arr = new Uint8Array(buffer)
                console.log(unit8Arr)
                const jmuxer = new JMuxer({
                    node: 'jmplayer',
                    mode: 'video',
                    flushingTime: 1000,
                    fps: 25,
                    debug: true,
                })

                jmuxer.feed({
                    video: uint8Arr
                })
            })
    
        }
    })
```

The brower console keeps throw tips " jmuxer.min.js:1 jmuxer: No. of frames of the last chunk: 0" and errors. 

The picture is here: 

![console_20201207165124](https://user-images.githubusercontent.com/24583874/101329645-9c22f880-38ac-11eb-9014-7c519d3589e7.png)

It will helps me a lot if you point some directions that where wents wrong and what kind of background knowledges I should look up to solve this problem. Much thanks.

**Comment by samirkumardas** [comment]
First, move the instantiation of jmuxer outside of the `videoStream ` callback. It is creating a new instance every time.

**Comment by chendishen** [comment]
@samirkumardas Hello, excuse me, I recently used it to receive H264 video stream from websocket in the project of electron + react, but there will be no. of frames of the last chunk: 0 as mentioned above. I think it is because of the virtual dom of react that the update of video source is not successful, or is my use method wrong?

**Comment by chendishen** [comment]
this is my code
```
function videoInit (data) {
    /**
     * h264 video stream
     *  */
    if(!jmuxer.current){
      console.log('only initialization')
      jmuxer.current = new JMuxer({
        node: 'player',
        mode: 'video',
        debug: true,
        flushingTime: 10,
        fps: 20,
        debug: false
      });
    }else{
      let input = new Uint8Array(data);
      jmuxer.current.feed({
        video: input,
      });
    }
    // console.log('jmuxer',jmuxer.current)
  }

  useLayoutEffect(() => {
    console.log('camera',camera)
    if(camera.current){
      videoInit(camera.current);
    }
  }, [jmuxer, camera.current]);

  function onWSMessage(e){
    let d = new DataView(e);
    let dType = d.getUint8(0, false);
    if(dType == 0x01){
      // h264 video stream
      camera.current = e
    }else if(dType == 0x07){
      // video No
      console.log('get the camera')
      chooseCamera(d.getUint32(1, false))
    }
  }
```

**Comment by chendishen** [comment]
![image](https://user-images.githubusercontent.com/20769262/101433485-6b42d200-3945-11eb-8712-35b6e281e918.png)

**Comment by MistaHanyi** [comment]
> First, move the instantiation of jmuxer outside of the `videoStream ` callback. It is creating a new instance every time.

Thanks. What a fool of me not noticing that.

**Comment by MistaHanyi** [comment]
@samirkumardas I'm done. You can close the issus whenever you want. But there is another user posted some questions. Leave it to you. Anyway, thanks a lot.

**Comment by samirkumardas** [comment]
@chendishen it is not related to virtual dom.  It seems you are feeding a tiny chunk of data at a time that contains no picture frame sometimes. 

1. Does it render anything on the player?  
2. The flashing time is `10ms`. It is not getting enough data to be flashed actually.   Try with a larger value first like 500 or 1000 to see if it plays properly. 
3. Make sure your data is valid. Capture some data and write it into a file. Then play it [with this player](https://samirkumardas.github.io/jmuxer/h264_player.html)  or VLC player

**Comment by chendishen** [comment]
@samirkumardas Thanks. It's not really a virtual DOM problem.. This is because my video tag doesn't add muted autoplay = autoplay. After adding it,  I can use it...

**Comment by zhangpeibisha** [comment]
> @samirkumardas谢谢。这不是真正的虚拟 DOM 问题。这是因为我的视频标签没有添加静音自动播放 = 自动播放。添加后，我可以使用它...

Hello, what properties should be configured in the video tag ~ I also encountered the same problem as you ~
