### ISSUE TITLE
Starting the stream from the middle

### ISSUE THREAD

**Issue by kuzux** [samirkumardas/jmuxer#67]
We have a remote desktop system which already works (by sending encoded h264 data over a websocket and feeding that to jmuxer). What we are trying to develop is sending the same stream (without re-encoding) to secondary "viewer" clients. 

What we are doing is storing and sending the first chunk of the stream (which contains sps/pps data, I think) and then continuing by sending the encoded frames as they come along.

On the client side; we detect the first keyframe we receive (by its nalu type) and start feeding jmuxer after that keyframe. I tried writing the stream the client receives to a file and opening that file - Both ffmpeg and mplayer sucessfully process the file although they both complain about timestamps being missing.

After that, we are not sure what the problem is or if it is related to jmuxer at all.

**Comment by samirkumardas** [comment]
> On the client side; we detect the first keyframe we receive (by its nalu type) and start feeding jmuxer after that keyframe.
What about the other Nalus before the keyframe? The other frames e.g. SPS, PPS, etc. must be provided as well.  If you always provide the same copied chunk before the starting keyframe, it might not work because SPS, PPS may not remain the same across the full stream.

**Comment by kuzux** [comment]
That didn't work, either (Had the same result, the page does not play but we get a h264 stream that can be played when saved as a file

**Comment by samirkumardas** [comment]
Is the saved stream played by this player https://samirkumardas.github.io/jmuxer/h264_player.html ?
If not, can you share a saved file?

**Comment by kuzux** [comment]
Here's the archive that contains the h264 stream received by the page (saved as a file)

[de829d8c-dc47-448c-8656-d46e093eb212.zip](https://github.com/samirkumardas/jmuxer/files/5918641/de829d8c-dc47-448c-8656-d46e093eb212.zip)

**Comment by kuzux** [comment]
So, apparently that player can play the file as well

**Comment by samirkumardas** [comment]
I tried to play the file via VLC player but it did not play. Are you able to play it using VLC?

**Comment by kuzux** [comment]
vlc plays it only after renaming the file with .h264 extension

**Comment by kuzux** [comment]
alright, what we were doing wrong was passing the data as an arraybuffer instead of an uint8array, that fixed things
