### ISSUE TITLE
Cannot play h264 stream generated by OpenH264

### ISSUE THREAD

**Issue by kakashidinho** [samirkumardas/jmuxer#70]
I used OpenH264 to encode an H264 stream and write to .h264 file.
VLC can open it. However, jmuxer's H264 player sample cannot. From console, it kept saying `put segment (video): 1 dts: 0 gop: 192 second: 00:00` then stopped.
May I know what's wrong or what is currently unsupported?

**Comment by samirkumardas** [comment]
Can you play it using this player https://samirkumardas.github.io/jmuxer/h264_player.html ?
Can you share a h264 file?

**Comment by kakashidinho** [comment]
No, the player cannot play it as I said above. This is the file: https://1drv.ms/u/s!Au3ABfehsKzjgppZI6QBEOGvWZUv3A?e=K4LKSw

**Comment by samirkumardas** [comment]
It worked for me. 
1. In FF, it worked without any issues
2. In Chrome, change framerate to 50 or enter video duration 2, it plays well.  In chrome, I noticed earlier the same thing when it has few buffers to play.

**Comment by kakashidinho** [comment]
Ok thanks, so it seems this issue is due to Chrome' video player needs to buffer enough frames before playing?
That's good since I thought there would be some compatibility issues if I use OpenH264.
