### ISSUE TITLE
Demo project doesn't play in Safari 

### ISSUE THREAD

**Issue by pietrorea** [samirkumardas/jmuxer#71]
The demo project (`example/index.html`) plays in Chrome but not on Safari. I'm running Safari v14.0.3 on M1 Big Sur. The video player doesn't move past the image below.

<img width="580" alt="Screen Shot 2021-02-23 at 10 26 58 AM" src="https://user-images.githubusercontent.com/1264371/108865890-af975300-75c1-11eb-8a22-9344f0a7ef8c.png">

**Comment by samirkumardas** [comment]
It worked fine on my MAC Safari. I will try on Mac M1  when I get a chance.

**Comment by EricTop3** [comment]
> The demo project (`example/index.html`) plays in Chrome but not on Safari. I'm running Safari v14.0.3 on M1 Big Sur. The video player doesn't move past the image below.
> 
> <img alt="Screen Shot 2021-02-23 at 10 26 58 AM" width="580" src="https://user-images.githubusercontent.com/1264371/108865890-af975300-75c1-11eb-8a22-9344f0a7ef8c.png">

I have the same problem and want to know how to fix it

**Comment by witaly-iwanow** [comment]
It's definitely broken on Safari. I've tried both M1 and Intel macs, no luck. Interestingly it's only raw h264 playback demo failing (https://samirkumardas.github.io/jmuxer/h264_player.html) while https://samirkumardas.github.io/jmuxer/ works fine.

I suspect that Apple devs broke video-only fmp4 support at some point

**Comment by samirkumardas** [comment]
I also got the same problem. Will look into it when I have some free time. Thank you for the reporting.

**Comment by witaly-iwanow** [comment]
I'm trying to figure out what's wrong myself, but no luck so far. I did stumble upon this h264 video (it's from Google's MSE test suite) which works - it's a little shaky, but still works most of the times - and I have no idea why other videos won't work
[car.h264.zip](https://github.com/samirkumardas/jmuxer/files/9712957/car.h264.zip)

**Comment by samirkumardas** [comment]
yes, you've spotted it out correctly. Nothing problem with jMuxer, it needs to provide data in smaller chunks instead of shoving the whole data once.
