### ISSUE TITLE
Audio has a 30-40 second lag when coming from different source from video

### ISSUE THREAD

**Issue by pietrorea** [samirkumardas/jmuxer#72]
I'm sending H264 video and AAC audio buffers to `jMuxer` on the browser. The video and audio come from different "live" sources. When I do this, the video starts playing right away but audio takes at least 30 seconds to start playing. I'm not setting "duration" on the `jMuxer` instance, so it's inferring it from the buffers.

Separately, the Media tab in Chrome Developer tools says that some timestamps are out of sync:

"Failed to reconcile encoded audio times with decoded output.". 

This is the place in the Chromium code where that gets logged: https://chromium.googlesource.com/experimental/chromium/src/+/refs/wip/bajones/webvr/media/filters/audio_timestamp_validator.cc

 I would expect the audio to start playing right away once the audio buffer is big enough. Any tips debugging this would be appreciated.

**Comment by samirkumardas** [comment]
> I'm not setting "duration" on the jMuxer instance, so it's inferring it from the buffers.
Unfortunately, it is not taking timing information from the buffer. If no timing information is provided, jMuxer runs the video at 30/fps

If it gets correct audio data, it should play immediately. jMuxer has nothing to do with it, the browser plays it.

You can capture some audio data in a file and try playing using a player e.g VLC player to see it plays immediately. 

Don't you feed both audio and video chunk at the same time?

**Comment by pietrorea** [comment]
@samirkumardas thank you for the info. 

`You can capture some audio data in a file and try playing using a player e.g VLC player to see it plays immediately.`
I can capture audio and save it into a file from the server and it plays immediately.

`Don't you feed both audio and video chunk at the same time?`
Yes, I'm using the same `feed` method to add chunks to the video buffer and the audio buffer.
