### ISSUE TITLE
Compatibility with stream containing only NDR NRI and IRD NRI frames

### ISSUE THREAD

**Issue by DrMiaow** [samirkumardas/jmuxer#73]
I'm attempting to use this library as a stream source from a raspberry pi camera using https://github.com/pimterry/raspivid-stream

It only appears to create NDR NRI and IRD NRI frames.

I've had a go at injecting `width` `height` and `codec` into `H264Remuxer:mp4track` and setting `H264Remuxer:readyToDecode` to true at the right point in the workflow. Finding that right point is finding to be hard. My best attempt yet has ended up with a `buffer error` from MSE. 

Do you have any suggestions please as to how I could achieve this?

**Comment by DrMiaow** [comment]
I just tried another library. https://www.npmjs.com/package/pi-camera-connect

Same issue. Seems to be a common case on the pi so far for me.

**Comment by DrMiaow** [comment]
I managed to find the common element for those two libs and there is an `inline` option for `[raspivid](https://www.raspberrypi.org/documentation/raspbian/applications/camera.md)` which thankfully seems to to what it says on the box `--inline,   -ih     Insert PPS, SPS headers`. Which solves the issue. 

I do see a lot of error messages. 

![image](https://user-images.githubusercontent.com/31360/112738355-270e2880-8f5a-11eb-89bc-1f3ba4f6c9cf.png)

* My debugging added `data.video.length`.

My guess is this error message will fire for me if `[slices, left] = H264Parser.extractNALu(data.video);` gets nothing in the current buffer, although it might get something when the rest of the buffer arrives? Or is there a requirement that chunks have to be complete and I am actually dropping frames?

**Comment by samirkumardas** [comment]
I always suggest doing one thing, capture some buffer and write in a file. Now try to play it using the VLC player, the VLC player can play it but jMuxer not, then it should be jMuxer issue. Please share the file in that case.
