### ISSUE TITLE
Is it possible to save the video as mp4 file ? 

### ISSUE THREAD

**Issue by tlecoz** [samirkumardas/jmuxer#80]
Hello 
I would like to know if it's possible to use jmuxer to generate a mp4 file
If yes, can you add an example to show how to proceed please 

Thanks for reading (and for all your great work ! )

**Comment by samirkumardas** [comment]
Possible on node environment

**Comment by tlecoz** [comment]
Thank you for your message ! 

How can I do it ?

**Comment by chipweinberger** [comment]
I'd like more help with this too!
