### ISSUE TITLE
Framedropping

### ISSUE THREAD

**Issue by borconi** [samirkumardas/jmuxer#85]
Hi.

Thanks for this nice tool.
Quick question, will it be possible to implement frame dropping? My client is a very low end computer and playback falls behind significantly. My server is sending NAL units, so I can't implement dropping logic there as it will cause corruption in the video stream, and no I don't really have the possibility to re-encode at a lower FPS. 

Basically the video FPS is 30 but the client can playback somewhere around 10-15 fps... so I need to somehow drop the rest of the frames.

Thanks for any tip

**Comment by samirkumardas** [comment]
I assume you have a dropping algorithm in your mind and you want to apply it in jMuxer. Is that correct?

**Comment by borconi** [comment]
Not really sadly.... my initial though was to simply drop the received bytes if the muxer is busy but that corrupts the video. And to the best of my knowledge there is no way we can determine from a NAL unit when the next frame starts.... if that can be obtained then I can simply not pass data to the muxer till the next frame.... 

Tried now to lower the video to 720p and that seems to make a massive difference... so maybe I can use that will be doing more complex testings later on today.
