### ISSUE TITLE
Any way to make this work with codecs `vp9` video and `mp4a` audio?

### ISSUE THREAD

**Issue by italodeandra** [samirkumardas/jmuxer#90]
Hi team,

I need to play a video (webm - vp9) and an audio (m4a - mp4a) file at the same time on a browser that only accepts one media playing at a time (if I try to play them simultaneously on separate <video> and <audio> elements, the previous gets paused automatically).

So my alternative was trying to mux them together, I found this library but I'm not sure if it will work with the codecs I have.

**Comment by samirkumardas** [comment]
It only supports the h264 video codec and ACC audio codec, unfortunately.
