### ISSUE TITLE
Windows Chrome and Processing Latency

### ISSUE THREAD

**Issue by sanalpencere** [samirkumardas/jmuxer#91]
I am not hundred percent sure this issue is related to `jmuxer`. I appreciate any guidance you might offer.

We're using `jmuxer` for live streaming. Our streaming machines have two types of encoders. One of them is Nvidia, another one is OpenH264. 

The problem is with Chrome on Windows. I think that processing takes a long time and it causes latency. But the weird part is if I close hardware acceleration from Chrome settings. There is no problem. Also If I use OpenH264 encoder, there is no problem too. Also If I force Windows to use the Nvidia graphics card for Chrome, There is no problem too.

Let me give you our encoder settings too:

NVIDIA
- Bitrate: Between 4Mbit - 16Mbit (It is optimal)
- Profile: Main
- Preset: LowLatencyHighPerformance
- RC Mode: VariableBitrate
- FPS: 30
- IdrPeriod: 10
- QP: 20
- Target Quality: 20

OpenH264
- Bitrate: Between 4Mbit - 16Mbit (It is optimal)
- Profile: Baseline
- Usage Type: SCREEN_CONTENT_REAL_TIME
- IdrPeriod: 10

**Comment by samirkumardas** [comment]
It seems to be a similar issue #84 
Also, there is a difference in profile. Can you try with baseline profile when you use NVIDIA to be sure if it is related to the problem?

**Comment by sanalpencere** [comment]
> It seems to be a similar issue #84 Also, there is a difference in profile. Can you try with baseline profile when you use NVIDIA to be sure if it is related to the problem?

Of course, I will try it again. I remember I tried with Baseline profile and got the same problem. I will try it again to be hundred percent sure.

The most annoying thing is also when I close hardware-accelerated decode from chrome flags. The problem is gone.
