### ISSUE TITLE
Can you support the timestamp?

### ISSUE THREAD

**Issue by chenchenwuai** [samirkumardas/jmuxer#92]
like this
```
jmuxer.feed({
   video: video,
   timestamp: timestamp
});
```

**Comment by samirkumardas** [comment]
jmuxer does not support it. You have to calculate the duration before feeding to jmuxer.

**Comment by zhang22113** [comment]
> 像这样
> 
> ```
> jmuxer.feed({
>    video: video,
>    timestamp: timestamp
> });
> ```

请问可以交流一下关于该项目的用法吗？
