### ISSUE TITLE
not support h264 substream ?

### ISSUE THREAD

**Issue by sinianzhiren** [samirkumardas/jmuxer#93]
Excuse me，Does this library not support H264 substream play？

**Comment by samirkumardas** [comment]
It is supposed to work. If you face any issues in playing, please provide a sample file containing your streaming. 
You can try playing that file using the VLC player.  If the VLC player can play but jmuxer does not, please give the file.

**Comment by sinianzhiren** [comment]
@samirkumardas Thank you for your last reply. I tried to upload the following video to the official online demo, but it can't be played, but it can be played with vlc. Since github issues do not support uploading h264 bare streams, I have provided an address to download this video. 
 [https://zhaitaoyigou.com/smoke.264](url)
this video is the sub-stream data obtained from Haikang camera.

**Comment by sinianzhiren** [comment]
@samirkumardas The same video can be played if it is the main stream h264 file from the camera and uploaded to the official demo address.

**Comment by samirkumardas** [comment]
I can play the file with jmuxer https://samirkumardas.github.io/jmuxer/h264_player.html

**Comment by sinianzhiren** [comment]
@samirkumardas Thank you. I've found the reason. The sub streams from some cameras are encoded in h265 format. Do you plan to support h265 format encoding in this library
